version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-db-is
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

