version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-db-is11
    restart: always
    profiles: ["storage"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jira:
    container_name: jira
    build: 
      dockerfile: jira.Dockerfile
    restart: always
    environment:
      - JIRA_DB_TYPE=postgresql
      - JIRA_DB_URL=jdbc:postgresql://postgres:5432/jiradb
      - JIRA_DB_USER=postgres
      - JIRA_DB_PASSWORD=postgres
    profiles: ["storage"]
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - jira_data:/var/atlassian/application-data/jira

  is-lab:
    build: .
    profiles: ["app"]
    depends_on:
      - postgres
      - jira
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JIRA_URL=http://jira:8080
      - JIRA_USERNAME=admin
      - JIRA_PASSWORD=admin
    ports:
      - "8080:8080"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    restart: always
    profiles: ["storage"]
    ports:
      - "8161:8161"    # Web Console
      - "61616:61616"  # TCP
      - "61613:61613"  # STOMP
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin

volumes:
  postgres_data:
  jira_data:
