spring:
  application:
    name: firstLabBLPS

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      transaction:
        coordinator_class: jta
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform

  jta:
    enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  cloud:
    aws:
      credentials:
        access-key: ${YANDEX_CLOUD_ACCESS_KEY}
        secret-key: ${YANDEX_CLOUD_SECRET_KEY}
      region:
        static: ru-central1
      endpoint: https://storage.yandexcloud.net

  activemq:
    broker-url: tcp://localhost:61613
    user: admin
    password: admin
    pool:
      enabled: false

application:
  yandex:
    bucket:
      name: is-bucket
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${APPLICATION_SECURITY_EXPIRATION:86400000} # a day
    unique-password-constraint: ${APPLICATION_SECURITY_UNIQUE_PASSWORD_CONSTRAINT:false}

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.jboss.narayana: DEBUG
    com.arjuna: DEBUG


admin: # логин и пароль главного админа, который изначально есть в системе
  username: admin_main
  password: admin_main


thymeleaf:
  enabled: true
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 8982

# Jira Configuration
jira:
  url: http://localhost:8081
  username: ${JIRA_SERVICE_ACCOUNT_USERNAME:jboss}
  password: ${JIRA_SERVICE_ACCOUNT_PASSWORD:jboss}
  project.key: COMP 

topic:
  name:
    moder-service-request: moderationTopic
    moder-service-response: moderationTopicResponse

# Camunda Configuration
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    database:
      type: postgres
    webapp:
      application-path: /camunda
      port: 8192
    authorization:
      enabled: true
    job-execution:
      enabled: true
    metrics:
      enabled: true
    history-level: full
    process-engine-name: default
    form:
      enabled: true
      resource-path: classpath:forms/
    generic-properties:
      properties:
        historyTimeToLive: P1D