spring:
  application:
    name: firstLabIS

  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      eclipselink:
        weaving: static
        ddl-generation: update
    database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${APPLICATION_SECURITY_EXPIRATION:86400000} # a day
    unique-password-constraint: ${APPLICATION_SECURITY_UNIQUE_PASSWORD_CONSTRAINT:false}

logging:
  level:
    org.zalando.logbook: TRACE

admin: # логин и пароль главного админа, который изначально есть в системе
  username: admin_main
  password: admin_main